### ISSUE TITLE
Restriction of `Field` are not applied to the `examples` function

### ISSUE THREAD

**Issue by raui100** [JakobGM/patito#13]
The following code raises an `ValidationError` because `a` is assigned `-0.5` as float by `Product.examples()` even though `a` is restricted to be `>=0.0`:

```python
import patito as pt
class Product(pt.Model):
    a: float = pt.Field(ge=0.0)


if __name__ == "__main__":
    p = Product.examples()
    print(p["a"][0])  # "-0.5"
    Product.validate(Product.examples())  # ValidationError
```

**Comment by ion-elgreco** [comment]
Yup, running into the same issue now. Now I've had to manually provide a value in the examples for these fields. However the issue seems to be only for `ge`

Issue is here: https://github.com/JakobGM/patito/blob/77923db45194acea7de49be8194100870833e982/src/patito/pydantic.py#L759-L762C4

I'll open up a pr for it

**Comment by raui100** [comment]
Has been fixed!
